language: node_js
# enable container-based builds
# see (http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)
sudo: false
# Cache ruby gems used by S3 deployment
cache:
  directories:
  - node_modules
node_js:
- 'node'
before_script:
- export PATH=$PWD/node_modules/.bin:$PATH
- make update-package-version
script:
- make lint
- npm test
- NODE_ENV=production make webui-build chrome-extension firefox-extension
- make test-package
deploy:
- provider: script
  script: utils/deploy.js
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJLAC2I2QPV6E33GA
  # AWS_SECRET_KEY
  - secure: "jQ3cFyDDk97Kh1fDwpSTCKTGIHljmTBTmV+4LWLliMNk8LpGuOGjbZRPNNHc+12kqz0i0wd4HaX6Uy8le5RMAQkunIE3r44k9z+9ciCSB4Nznq+AigpEVqgAjT/+MkIHEjCVXPmIeutxKoLY2iZHpHZRfsQbUI7376hIZw2CGQE="
  - CHROME_EXT_CLIENT_ID=663008561130-bgbo9tvbnr7j1ufrfuf52r4k3g8t9j9n.apps.googleusercontent.com
  - CHROME_EXT_APP_ID=olcdnhbhbfgncnocdfojpdjbododkimk
  # CHROME_EXT_REFRESH_TOKEN
  - secure: "XtPKZiXhH10NAVfDy1VWkxO0vptXEXLGQo/mmO1zI7HtMgfwwFqzW2AjZk5Ttto0gPzzMgYjUO5NqvUevUjSWJYjPxgB48uLR/UDAXbqzO3G/f/Xgu3+sgj971Pq3n5a3djeId6uGzYryowM7yFOek12VvZT4bYXRPVaP/1ovSw="
  # CHROME_EXT_CLIENT_SECRET
  - secure: NyDSq2y6xkHzFTTnoZuLrLfIdEmSzNTEQX9vQQCNyGfCWDbN4AYQd2whYAYV0IUaKdOh5/p+ixYvIaodjVol5ixRZ0p1R3IiqRfwV7YPum10goPiAb9e8D+tNgryz0SUMBNtJBT07yc3NsrTZAAsZfEb0ME4Emdp7O9C8q4d9pk=
  # NPM_AUTH_TOKEN
  - secure: "mZc/QM0FmeGwCPrUHsInrXp9gBXkyezEcioM0fyjmajboqerjfjz4uzn0C4iGEYXL5SBEbEuTcFfnaa3Mtuy6ftWrj5l0VbcimHgiwy20+FFeM5cJE4eC6uwnY6BNVECF0KwHM8qIMwY1w94mIVQCg8+P7rzE74xnUVl45k7BEE="
  # FIREFOX_AMO_KEY
  - secure: "MbJcrFfIiL9rpBDX1ZDIBkd3nVUwB80OT77A0HcFpVMe79yAKbk5Io9eH3are4i1amn8CUnYXalbMCmGZBUx6EagmYAEhWqenitnpeAQit/MPUMTdx9PHmS+12pWeY/oztVz5fN4WC9f0uzP3y3+e+QfNy211lwWGUkJhDdBqIc="
  # FIREFOX_AMO_SECRET
  - secure: "PGV1fgLrVM6xClcYolu/vz6CnV0RYKtXiSgUtUFPes+OYKFscJIvZ5mBUp6y7MuaGLtNBV9spAAlXwz6lEl4yyq8z/oLfxTmiu+9zf4kvlzr16/6ADOOEk0CWDBJHtGd55wAabQDQgP8hbps7oWrGzrEGQOWn9NZXXir4kiRBTs="
